name: 509finalenv
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - arrow-cpp=6.0.0
  - async-timeout=4.0.1
  - attrs=21.2.0
  - aws-c-auth=0.6.4
  - aws-c-cal=0.5.12
  - aws-c-common=0.6.11
  - aws-c-compression=0.2.14
  - aws-c-event-stream=0.2.7
  - aws-c-http=0.6.6
  - aws-c-io=0.10.9
  - aws-c-mqtt=0.7.8
  - aws-c-s3=0.1.27
  - aws-checksums=0.1.12
  - aws-crt-cpp=0.17.1
  - aws-sdk-cpp=1.9.120
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - blinker=1.4
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - chardet=4.0.0
  - charset-normalizer=2.0.7
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=35.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - decorator=5.1.0
  - expat=2.4.1
  - fiona=1.8.20
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.28.1
  - freetype=2.10.4
  - freexl=1.0.6
  - frozenlist=1.2.0
  - gdal=3.4.0
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glog=0.5.0
  - google-api-core=1.31.2
  - google-api-core-grpc=1.31.2
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-cloud-bigquery=2.30.1
  - google-cloud-bigquery-core=2.30.1
  - google-cloud-bigquery-storage-core=2.10.0
  - google-cloud-core=1.7.2
  - google-cloud-storage=1.42.3
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.53.0
  - grpc-cpp=1.41.1
  - grpcio=1.42.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=2.10
  - intel-openmp=2021.4.0
  - ipython=7.29.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcst=0.3.22
  - libcurl=7.80.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgdal=3.4.0
  - libglib=2.70.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.18.1
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libutf8proc=2.6.1
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - multidict=5.2.0
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - networkx=2.6.3
  - numpy=1.21.4
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.4
  - pandas-gbq=0.16.0
  - parquet-cpp=1.5.1=2
  - parso=0.8.2
  - pathlib=1.0.1
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - poppler=21.11.0
  - poppler-data=0.4.11
  - postgresql=13.5
  - proj=8.2.0
  - prompt-toolkit=3.0.22
  - proto-plus=1.19.6
  - protobuf=3.18.1
  - pyarrow=6.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydata-google-auth=1.2.0
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyproj=3.3.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2021.11.01
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - rtree=0.9.7
  - scikit-learn=1.0.1
  - scipy=1.7.2
  - setuptools=59.2.0
  - shapely=1.8.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - tbb=2021.4.0
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=4.0.0
  - typing_extensions=4.0.0
  - typing_inspect=0.7.1
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xyzservices=2021.11.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zlib=1.2.11
  - zstd=1.5.0
variables:
  GOOGLE_APPLICATION_CREDENTIALS: /Users/lexi/Desktop/UPENN_COURSE/MUSA_509/Final/covidDashboard/key/musa509cloudcomputing-89c68465f510.json
  PIPELINE_DATA_BUCKET: final
  cloud: cloud
  key/musa509cloudcomputing-89c68465f510.json: key/musa509cloudcomputing-89c68465f510.json
